# Generated by Django 3.0.7 on 2021-03-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20210309_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='chapter_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='novel',
            name='view_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
