# Generated by Django 3.0.7 on 2021-03-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20210309_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='bookmark_count',
            field=models.IntegerField(default=0),
        ),
    ]
