# Generated by Django 3.0.7 on 2021-03-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_novel_number_of_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
