# Generated by Django 3.0.7 on 2021-03-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_novel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='category',
        ),
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ManyToManyField(blank=True, to='novel.Category'),
        ),
    ]
