# Generated by Django 3.0.7 on 2021-03-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_auto_20210309_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
