# Generated by Django 3.0.7 on 2021-03-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_novel_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.Novel'),
        ),
    ]
