# Generated by Django 3.0.7 on 2021-03-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0012_auto_20210309_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
