# Generated by Django 3.0.7 on 2021-03-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0013_auto_20210310_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='bookmark_count',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='chapter_per_week',
        ),
    ]
