# Generated by Django 3.0.7 on 2021-03-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0014_auto_20210310_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
